### ISSUE TITLE
No LICENSE File

### ISSUE THREAD

**Issue by ramithp** [episodeyang/ml_logger#16]
The project needs a LICENSE file for declaring its fair-use policy. Could one be added to indicate how we can use this repository?

https://choosealicense.com/no-permission/
No license technically does not allow any re-use whatsoever.

Thanks.

**Comment by episodeyang** [comment]
Thanks for pointing out this oversight! I will add MIT for now unless there are objections. I will also add a contributor file.

**Comment by episodeyang** [comment]
LICENSE FILE has been added, closing this as part of the PR :)

@ramithp, check out this new dashboard!!

![ml-dash v3](https://user-images.githubusercontent.com/630490/60468135-83b9a380-9c0d-11e9-975d-bf45027472c7.gif)
