### ISSUE TITLE
Command argument escaping

### ISSUE THREAD

**Issue by pimdh** [episodeyang/ml_logger#5]
Be sure to escape shell arguments.
```logger.git_rev('HEAD; rm -rf /')```
https://github.com/episodeyang/ml_logger/blob/5b6088d5e2528680fa3aeeff29857174c274127a/ml_logger/ml_logger.py#L167:L180

**Comment by episodeyang** [comment]
Thanks @pimdh :)

Shall I use regex to validate? PR is welcomed :)

**Comment by pimdh** [comment]
Better is to remove `shell=True`, as you don't need it and to provide the arguments separately:
```
subprocess.check_output(['git', 'diff', 'HEAD'])
```
See https://docs.python.org/3/library/subprocess.html#security-considerations

**Comment by episodeyang** [comment]
Addressed in new release: v0.1.33

**Comment by episodeyang** [comment]
@pimdh You can find the changes here: https://github.com/episodeyang/ml_logger/commit/ef8a2743e39ad7e971d0f9a7e25c57b82e67eedd
